export const colors = [
  { id: 1, name: "Rojo" },
  { id: 2, name: "Verde" },
  { id: 3, name: "Azul" },
  { id: 4, name: "Amarillo" },
];

export const animals = [
  { id: 1, name: "Tiburon" },
  { id: 2, name: "Carnero" },
  { id: 3, name: "Toro" },
  { id: 4, name: "Ciempies" },
  { id: 5, name: "Alacran" },
  { id: 6, name: "Leon" },
  { id: 7, name: "Rana" },
  { id: 8, name: "Perico" },
  { id: 9, name: "Raton" },
  { id: 10, name: "Aguila" },
  { id: 11, name: "Tigre" },
  { id: 12, name: "Gato" },
  { id: 13, name: "Caballo" },
  { id: 14, name: "Mono" },
  { id: 15, name: "Paloma" },
  { id: 16, name: "Zorro" },
  { id: 17, name: "Oso" },
  { id: 18, name: "Pavo" },
  { id: 19, name: "Burro" },
  { id: 20, name: "Chivo" },
  { id: 21, name: "Cochino" },
  { id: 22, name: "Gallo" },
  { id: 23, name: "Camello" },
  { id: 24, name: "Cebra" },
  { id: 25, name: "Iguana" },
  { id: 26, name: "Gallina" },
  { id: 27, name: "Vaca" },
  { id: 28, name: "Perro" },
  { id: 29, name: "Zamuro" },
  { id: 30, name: "Elefante" },
  { id: 31, name: "Caiman" },
  { id: 32, name: "Lapa" },
  { id: 33, name: "Ardilla" },
  { id: 34, name: "Pescado" },
  { id: 35, name: "Venado" },
  { id: 36, name: "Pantera" },
  { id: 37, name: "Culebra" },
];

export const banks = [
  {
    id: "1",
    name: "MERCANTIL BANCO UNIVERSAL",
    code: "0105",
  },
  { id: "2", name: "BANCO DE VENEZUELA S.A. BANCO UNIVERSAL", code: "0102" },
  {
    id: "3",
    name: "VENEZOLANO DE CREDITO, S.A. BANCO UNIVERSAL",
    code: "0104",
  },
  { id: "4", name: "BANCO PROVINCIAL S.A. BANCO UNIVERSAL", code: "0108" },
  { id: "5", name: "BANCO DEL CARIBE S.A.C.A.", code: "0114" },
  { id: "6", name: "BANCO EXTERIOR, C.A.", code: "0115" },
  { id: "7", name: "BANCO OCCIDENTAL DE DESCUENTO S.A.C.A.", code: "0116" },
  { id: "8", name: "BANCO CARONI, C.A. BANCO UNIVERSAL", code: "0128" },
  { id: "9", name: "BANESCO BANCO UNIVERSAL", code: "0134" },
  { id: "10", name: "BANCO SOFITASA", code: "0137" },
  { id: "11", name: "BANCO PLAZA", code: "0138" },
  { id: "12", name: "FONDO COMUN, C.A. BANCO UNIVERSAL", code: "0151" },
  { id: "13", name: "100% BANCO, BANCO UNIVERSAL C.A.  ", code: "0156" },
  { id: "14", name: "DEL SUR BANCO UNIVERSAL, C.A.  ", code: "0157" },
  { id: "15", name: "BANCO DEL TESORO", code: "0163" },
  { id: "16", name: "BANCO AGRICOLA DE VENEZUELA C.A.", code: "0166" },
  { id: "17", name: "BANCRECER S.A. BANCO MICROFINANCIERO", code: "0168" },
  { id: "18", name: "MIBANCO BANCO DE DESARROLLO", code: "0169" },
  { id: "19", name: "BANCO ACTIVO, C.A.", code: "0171" },
  { id: "20", name: "BANCAMIGA BANCO UNIVERSAL", code: "0172" },
  { id: "21", name: "BANPLUS BANCO UNIVERSAL, C.A.", code: "0174" },
  {
    id: "22",
    name: "	BANCO BICENTENARIO BANCO UNIVERSAL C.A.",
    code: "0175",
  },
  {
    id: "23",
    name: "BANCO DE LA FUERZA ARMADA NACIONAL BOLIVARIANA",
    code: "0177",
  },
  { id: "24", name: "BANCO NACIONAL DE CREDITO, C.A.", code: "0191" },
];

export const phones = [
  { id: "1", code: "0416" },
  { id: "2", code: "0426" },
  { id: "3", code: "0414" },
  { id: "4", code: "0424" },
  { id: "5", code: "0412" },
];
